
path: OBB_dataset             # dataset root dir
train: OBB_dataset/train       # train images (relative to 'path') 128 images
val: OBB_dataset/val      # val images (relative to 'path') 128 images
test:  OBB_dataset/test    


# Classes
names:
  0: .DOT
  1: 3M Peltor
  2: 3stepIT
  3: 4 Office
  4: 52bones
  5: AB Karl Hedin
  6: ABB
  7: AF Gruppen
  8: AGB Service
  9: AH Sport & Business
  10: AHNVIKS
  11: AJ Produkter
  12: ALT
  13: AVIX
  14: Abri
  15: Adidas logo
  16: Adidas tekst
  17: Advokatfirman Landerdahl
  18: Ahlberg bil
  19: AllOffice
  20: AllTransport
  21: Alvelid Engineering
  22: Alvinssons AB
  23: Amokabel
  24: ApQ
  25: Aprofit SE
  26: Arbesko
  27: Arken
  28: Aros Kapital
  29: Asfalt i Göteborg AB
  30: Asplunds Bygg
  31: Assemblin
  32: Audicom Pendax
  33: Auktionsbyrån Effecta AB
  34: Autocirc
  35: Avgasar & Renar
  36: B Bodin Bygg & Byggledning AB
  37: B el & tele
  38: BBM
  39: BBS Stål & Metaller
  40: BDS
  41: BLT
  42: BOA
  43: BRA
  44: BST
  45: BUFAB
  46: BabyBjörn
  47: Babylon Pizzeria
  48: Bad & Varme
  49: Barometern
  50: Bauhaus
  51: Beans in Cup
  52: Beijer Byggmaterial
  53: Bemanningspoolen
  54: Bendt Bil
  55: Bergkvarabuss
  56: Best Western
  57: Betonghål
  58: Betongkompaniet i Stockholm AB
  59: Betongteknik i Mälardalen AB
  60: Bevego
  61: Billy & Dennis
  62: Bioms AB
  63: Biotage
  64: Bjäre Chips
  65: Björklunds Kafferosteri
  66: Björklunds Kafferosteri tekst
  67: Bloms AB
  68: Blyckert & Börjesson Måleri AB
  69: Blåkläder
  70: BoViva
  71: Boards
  72: Bofast
  73: Bogstedt Bil
  74: Boozt
  75: Borgstena of Sweden
  76: Borohus
  77: Borås MurningsArbeten
  78: Borås Stad
  79: Borås Tidning
  80: Borås Truckservice
  81: Bostjärnan
  82: Brandtown
  83: Bravida
  84: Bredbandsval.se
  85: Bricmate
  86: Brion
  87: Brixo
  88: Brunna Schakt
  89: Bygg Construct
  90: Bygg-Bröderna S AB
  91: Böda Sand
  92: Börjessons
  93: C Land Logistics
  94: CA Fastigheter
  95: CLN Athletics
  96: CS Maskin
  97: CTC Värmepumpar
  98: CWS
  99: Carpenter
  100: Castellum
  101: Cequred Security
  102: Cernera
  103: Cityfastigheter
  104: ClickitUp
  105: Clinton
  106: Coca Cola
  107: Condesign
  108: Conductus AB
  109: Coop
  110: Coor
  111: Corpay
  112: Craft
  113: Craft tekst
  114: Craftor
  115: Cramo
  116: Crowe
  117: Cuebid
  118: Cupra
  119: DOXA
  120: DS Smith
  121: Dahl
  122: Dahl logo
  123: Daloc
  124: Demo Group
  125: Dick Johansson Skogstransporter AB
  126: Din Maskin
  127: Dinner 22
  128: Direct Larm & Lås
  129: Djurö Grävmaskiner AB
  130: Domtrappkällaren
  131: DynaMate
  132: Däck Partner
  133: EA
  134: EAB
  135: EB Road Cargo
  136: EFAB
  137: EL & Energioptimering
  138: EL Man
  139: EL VVS
  140: ELAK
  141: EXE Måleri
  142: EXIN
  143: Easy Coffee
  144: Easypartner
  145: Effektiv
  146: Ekerum Resort Öland
  147: Eksjöhus
  148: El Linjen AB
  149: Electrolux
  150: Eleda
  151: Elektrikerna i Nybro
  152: Elektriske Svea
  153: Elgiganten
  154: Elgrossisten Holmro
  155: Elitdecor
  156: Elite Grand Hotel
  157: Elkejdan
  158: Ellos
  159: Ellénius Buss
  160: Elon
  161: Enkla Elbolaget
  162: Ergoseat
  163: Ernst Textil
  164: Escape Travel
  165: Estrella
  166: Exceed
  167: Exiso
  168: Extra
  169: FR Fastighetsservice
  170: FSAB
  171: FVB
  172: Falkeskog
  173: Fameco
  174: Fat21
  175: Fem Hjärtan Fastigheter
  176: Finlarm
  177: Finnveden NU
  178: Finnvedens Expresstransport
  179: Finnvedens Trafikskola
  180: Finnvedsbostäder
  181: Flinks
  182: Flytgolv i Landskrona AB
  183: Folie & Papper
  184: Forenede Care
  185: Formenta
  186: Forza football
  187: Fotriktigt
  188: Four Office
  189: Frank Bistro
  190: Fransson Bygg AB
  191: Frejs
  192: Front Fasadgruppen
  193: Fyhrs
  194: GA
  195: GBJ bygg
  196: GDL
  197: GE Bäst
  198: GN Logistcs
  199: GN Transport
  200: GOTSAFE
  201: Gaismeister AB
  202: Garo
  203: Getinge
  204: Getinge logo
  205: Gevab Group
  206: GipsProffsen
  207: Gjuteriteknik
  208: Gjuteriteknik tekst
  209: Glimstedt
  210: Golvabia
  211: Good Advice
  212: Gorilla Glue
  213: Gothia Cup
  214: Guldfågeln
  215: Gunnars Maskiner
  216: Gäsene Mejeri
  217: Göteborgs Metallpartier
  218: HECO
  219: HFAB
  220: HJT Service AB
  221: HSE
  222: HTC Högtryckscenter i Väst AB
  223: Habo
  224: Halmstad
  225: Halmstad Kakelhus
  226: Halmstad stenhus
  227: Hammarby Construction AB
  228: Hammarstedt's Kyl & Inneklimat AB
  229: Handelsbanken
  230: HangOn
  231: Hanninge Terrazzology AB
  232: Hansson Kapell AB
  233: Harry Berglund Förvaltnings AB
  234: Herrljunga cider
  235: Hestra
  236: Hisstech AB
  237: Hitachi Energy
  238: Hogbergs Buss AB Uppsala
  239: Holmbergs
  240: Holmen
  241: HomeMaid
  242: Hotel Carlshamn
  243: Hotel Plaza
  244: Hugo
  245: Hulten
  246: Humidus
  247: Husvagns Expo
  248: Hydroscand
  249: Hygienteknik
  250: Hylte
  251: Hyrex
  252: Härryda Karlsson
  253: Hållanders Sägverk AB
  254: Högberg Buss AB
  255: Högbergs Buss AB
  256: ICA
  257: ICA Bomben
  258: ICA City
  259: ICA Kvantum
  260: ICA Supermarket
  261: IGS Capital
  262: IP Produkter AB
  263: IR
  264: ITS
  265: Idealtryck
  266: Ifmetall
  267: InfoPrint
  268: Infometric
  269: Infoservice
  270: InfraCom
  271: Infrakraft
  272: Inneklimat Värnamo
  273: Input Interiör
  274: Intersport
  275: Isobetong
  276: Ivar Svensson Trafik AB
  277: J&S Markservice AB
  278: JOCR Media
  279: Jisotech
  280: JoelJolina
  281: Jonab
  282: Jour
  283: Jowema
  284: Jump Yard
  285: Järletoft Bygg
  286: Järngrinden
  287: K-Bygg
  288: K-G Paulssons Bär & Grönsaker AB
  289: K-V Bygg
  290: K-vagnen
  291: KAMA
  292: KYL Teknik
  293: Kadesjös
  294: Kalmar Kuvert
  295: Kalmar Sotning & Ventilation AB
  296: Kappahl
  297: Kappex AB
  298: Karaten
  299: Klara
  300: Klarin´s Rör
  301: Konradssons Kakel
  302: Konst Smide
  303: Kopparberg
  304: Kranpunkten
  305: Kristina
  306: Kundpartner
  307: Kvarteret GIRAFFEN
  308: Kvibergs Överskottslager AB
  309: Kvik
  310: Kvinner For Fred
  311: LF Invest AB
  312: LGL Construction
  313: LGP Byggservice AB
  314: LK Buss AB
  315: LKQ Atracco
  316: LM Stålteknik AB
  317: Lantmännen Agroetanol
  318: Larsson
  319: Larsson & Karlsson Elinstallationer AB
  320: Leads
  321: Leijon
  322: Lendo
  323: Lesjöfors
  324: Let´s Create
  325: Libergs Sweden AB
  326: Liljedahl
  327: Lillebil
  328: Lindab
  329: Lindbytvätten
  330: Little Italy Barbershop
  331: Locads
  332: Logomattan
  333: Loows Måleri
  334: Lotus Hotel Group
  335: Lundagrossisten
  336: Lundby Plåt
  337: Lundebergs Fastigheter
  338: Lundebergs Fastigheter logo
  339: Lundqvist EL
  340: Luthagens Livs ICA
  341: Lyckholms Elektriska
  342: Länsförsäkringar
  343: Lönneberga
  344: MABI
  345: MAX
  346: MBF AB
  347: MCR
  348: MFF Play
  349: MG
  350: MIN
  351: MMG Marine AB
  352: MOH-Maya
  353: Maksimer
  354: Malaco
  355: Malmqvist
  356: Marielunds VVS
  357: Markentreprenad
  358: Maskin & Verktyg
  359: Mataki
  360: Mattr
  361: Maxi
  362: Maxxis Tyres
  363: McDonald's
  364: Mediaflow
  365: Mella el
  366: Mellby Gård
  367: Mellinger Bil
  368: Mellinger Fastigheter
  369: Mercedes
  370: Meritum
  371: Metodgolv
  372: Mitsubishi
  373: Mix Megapol
  374: Mizuno
  375: Mobill
  376: Mocca Deli
  377: Molins
  378: Multi bygg
  379: Musiklageret
  380: Muskelcentrum
  381: Månsson Rör
  382: NLY Man
  383: NP Nilsson
  384: NSFastigheter
  385: NSgastro
  386: NTEX
  387: Nearyou
  388: Nike logo
  389: Nike tekst
  390: Nivika
  391: NordVPN
  392: Nordea
  393: Norden
  394: NordiQ Group
  395: Nordic Wellness
  396: Nordquist & Järnvall
  397: Nordström Advokater
  398: Norima
  399: Norrvidinge
  400: Norteam
  401: Norén & Lindholm
  402: Notar
  403: Nybloms
  404: Nybyggar'n AB
  405: Nyfosa
  406: Näbo Bygg
  407: Nöjd
  408: OCAB
  409: OHLSSONS
  410: OWB
  411: Oatly
  412: Office
  413: Olle Lind Golv AB
  414: One More
  415: OnePartnerGroup
  416: Optimera
  417: Oscar Hansson VVS
  418: Ottosson Truck
  419: Ove
  420: PEAB
  421: PULS
  422: PacsOn
  423: Panasonic
  424: Parker
  425: Paroy
  426: Passera
  427: Peas of Heaven
  428: Pepsi
  429: Picadeli
  430: Pinewood
  431: Platinumcars
  432: Plåtkompaniet
  433: Pontuz Löfgren
  434: Port Du Soleil
  435: Power Automation
  436: Pre Zero
  437: PreFast
  438: Prefabsystem
  439: Presto
  440: Prison Island
  441: Projob
  442: Pulsen
  443: Puma
  444: Puma tekst
  445: QTF
  446: RO-gruppen
  447: Railway System
  448: Ramirent
  449: Ramo
  450: Rasta
  451: Ravema
  452: Redeye
  453: Reformhus
  454: Rejlers
  455: Rendo
  456: Renova
  457: Renta
  458: Retur Papper Centralen
  459: Revisorsgruppen
  460: Rexel
  461: Rimeda
  462: Rivare
  463: Road Rental
  464: Rollup
  465: Rollup-Kungen
  466: Ronneby Brunn
  467: Roxtec
  468: Rudholm Group
  469: Ryds Bilglas
  470: SAB
  471: SDX
  472: SE sol
  473: SEFAB
  474: SGA
  475: SHARP
  476: SKAB
  477: SKYLT & NEON
  478: SRM Stål & Rörmontage
  479: STARK
  480: STC
  481: SVB
  482: SVEA
  483: SafeScaff
  484: Salboheds
  485: Saljfast
  486: Sandahls
  487: Sanering
  488: Sanero
  489: Sankt Jorgen Park
  490: Saschas Familjearbete AB
  491: Scandic
  492: Scania
  493: SealEco
  494: Sefina Pantbank
  495: Select
  496: Select logo
  497: Seniorarbeten
  498: Serneke
  499: Serve You
  500: Sfär
  501: Silvent
  502: Simplicity
  503: Sirius
  504: Sjömarkens Svets och Smide AB
  505: Skolon
  506: Skrot Centralen
  507: Skrotfrag
  508: Skubbet
  509: Skylt-Reklam
  510: Skyltproduktion
  511: Smart Rail
  512: Snickeriportalen
  513: Social Zense
  514: Solel
  515: Solhemsgruppen
  516: Sollentuna Emballagehantering AB
  517: Sparbanken
  518: Sparbanken tekst
  519: Spolpatrullen
  520: Sport Vision
  521: Sportringen
  522: Sportway
  523: Sportway logo
  524: Stadax
  525: Stadium
  526: Stadsporten
  527: Stayhot
  528: Steelpro
  529: Stema
  530: Stena
  531: Stena Fastigheter
  532: Stena Recycling
  533: Stena Stål
  534: Stenfastigheter
  535: StensbergsEl AB
  536: Stigma
  537: Storkökside
  538: Stranda
  539: Städ & Fönsterservice
  540: Ståthøga Verkstad AB
  541: Sultan Kolgrill & Meze
  542: Sundström Safety
  543: Sundtorps Gård
  544: Super Dæk
  545: SveBag
  546: Svenska Höjdbolaget
  547: Swedbank
  548: Sydställningar
  549: Sydsvenskan
  550: Syncify
  551: Säkra
  552: Säljfast
  553: Söderbergs Bil
  554: Södertörns Däckservice AB
  555: Sölvesborgs kommun
  556: TB Printsolutions
  557: TCL
  558: TF Bank
  559: TICTAC
  560: TISAB
  561: TISAB Tak
  562: TL Bygg
  563: TSG
  564: TTM
  565: Tammp
  566: Tarkett
  567: Team "G" EL & VVS AB
  568: Techno Skruv
  569: Tegnanders Fastighets AB
  570: Teknos
  571: TekoTryck
  572: Tele2
  573: Teleoption
  574: Telexia
  575: Telink
  576: The Central Bar
  577: The Mobile Life
  578: Thermia
  579: Thermia Värmepumpar
  580: Tillmobil
  581: Toarps Plåtslageri AB
  582: Torrbollen Home
  583: Toveksbil VW
  584: Toyo Tires
  585: Tranpenad
  586: Transschakt
  587: Trebolit
  588: Triller Mat & Bröd
  589: Troax
  590: Truecaller
  591: Tryck Cenrtum
  592: Tujo AB
  593: Turbo
  594: Tvättex
  595: Tången
  596: UCS IT Solutions
  597: UFS
  598: UGSAB
  599: Umbro
  600: Unibet
  601: Unisport
  602: Uponor
  603: Upplands Bilforum AB
  604: Uppsala Brygghus
  605: Uppsala Handelsstål
  606: Uppsala Kommun
  607: Upsala GK
  608: VMAR
  609: VVS Fålhagen
  610: Vaksala Måleri
  611: Vaksala Måleri logo
  612: Varbergs Stadshotell & Asia Spa
  613: Varis Förvaltning
  614: Ventex Entreprenad AB
  615: VicApta
  616: Victoria
  617: Villalivet
  618: Vinga Group
  619: Vinnergi
  620: Voky
  621: Volkswagen
  622: VärnaBo Fastigheter AB
  623: Värnamo Energi
  624: Värnamo Kommun
  625: Värnamo Nyheter
  626: Västerås Takentreprenad AB
  627: Västkust Stugan
  628: Västtak
  629: WD-40
  630: WebROPol
  631: Weber
  632: Wellness Studio
  633: Werna Sportfiske AB
  634: West Timber
  635: Wilson Creative
  636: Wilssons
  637: Winpos
  638: WinsthGolv & Kakel
  639: Wohlins
  640: Work System
  641: XL Bygg
  642: Yaskawa
  643: Zinkteknik
  644: advokatbyrån novum
  645: amber advokater
  646: amicus
  647: axelssons
  648: bemt
  649: duoplåt Plåtslageri
  650: eQuality Fönster AB
  651: easyform
  652: enigma
  653: everbrand sweden.
  654: exakta
  655: friskis
  656: ggmgastro
  657: gibon
  658: ginatricot
  659: granitor
  660: iLoq
  661: inkClub
  662: j:retail
  663: kreativ teknik
  664: kvdbil
  665: marching on together ab
  666: merinfo
  667: milael
  668: nominit
  669: sesol
  670: visolve
  671: Åke Ekstrand Byggnads
  672: Ångtvättbilen
  673: Årsta tak
  674: Östras Stenungsbageriet
  675: Øresundsbron
  676: Østuna Shackt & Transport AB
